const analysis_data = [
    {"variable_name":"play_in", 
        "analysis":[
            "Top Destinations - UEFA",
            "England, Germany, Spain, France, Italy together attract 44% of the World Cup players for professional football, with England as the top destination",
            "It follows that 92%-100% players representing four of these five countries (Italy does not qualify for the World Cup) play professionally either in their local leagues or leagues from these five destinations.",
            "Perhaps also due to proximity, other European teams Switzerland, Austria, Netherlands, Norway and Belgium also have 70% of their players playing professionally in these five destinations.",
            "Despite the distance, 77% of the players representing Senegal and Argentina also play in these top five destinations.",
            "You could explore the above observations by selecting these top five destinations on the legend panel to see the distributions of players playing there. To further delve into these five destinations, you could also see whether players play in the top leagues of these five destinations.",
            "Unsurprisingly, the next destination is Saudi Arabia given its massive investment in football, attracting players from 18 national teams on top of its own national team.",
            "With football probably still being euro-centric, all destinations under UEFA also attracts at least 22 out of 26 players from Ivory Coast, DR Congo, Ghana, Senegal, Cape Verde, Curacao and Japan",
            "Teams with most mixed destinations",
            "Nonetheless, it is not every team is looking up to destinations under UEFA. For example, Paraguay consists of most diverse group of players in terms of where they play professionally, and only one of them play in England.",
            "Bosnia and Herzegovina is another team with high diversity though all of them play in UEFA, and similar to the wonderfull Cape Verde with all but three players play there.", 
            "In contrast, AFC representatives except Australia, Japan, South Korea tend to play in their local leagues and thus a more homogenious team.", 
            "At the same time, European big teams Spain, Germany, England except France also tend to be playing in their own leagues and less diverse.",
            "It seems, therefore, if you already have a strong domestic league, it is common to have your representatives from there and it might not be a disadvantageous. But if your domestic league is not that strong yet, it would probably be advantageous to have players playing in other countries, as in the case of the better performing Asian representatives Japan and Australia. Is this mirroring general migration patterns, you would want to go to a country strong in the field you are pursuing if your country is not yet there? Possibly in the future, you would be able to bring back the experience?",
            "You could explore the above observations by clicking sort with most mixed teams on the legend panel." 
        ]},
        {"variable_name":"birth_place", 
            "analysis":[
                "Top Birth Place",
                "So much media has been focused on the fact that France 'produced' (pun intended) the most number of players in the World Cup. A closer look at those players also revealed some human migration trend in relataion to colonial past. Beside France national team itself, Algeria, Haiti, DR Congo, Senegal all have at least 10 players born in France, followed by Ivory Coast and Tunisia with 8 and 7 players respectively. All these countries used to be the colonised by France, it is likely that players' ancestors might have migrated to France either voluntary or forced slavery. Nonetheless, all these countries except DR Congo also have at least nine players born locally",
                "Similarly, another top 'producer' is Netherlands, which to some extent produced two teams in the world cup, Netherlands national team itself and Curacao, which used to be colonised by the Dutch. Nonetheless, Curacao does have a player born there, Chong and with the surname, you know, he is of Chinese descent. What a wonderful mix of culture!",
                "You could explore the above observations by selecting France and Netherlands on the legend.",
                "Most Mixed team",
                "Most interesting thing to observe is that Bosnia and Herzegovina, Qatar, Tunisia, Morrocco, Cape Verde seem to have most mixed of players born in different countries. Given its history, quite a few players representing Bosnia and Herzegovina players come from countries breaking up from Yugoslavia.", 
                "The unexplained surprise to me is that of Qatar which have players born in quite a diverse place including Egypt, Portugal, Brazil, Senegal, Ghana, Sudan, Tunisia, France, Belgium and Algeria. Nonetheless, all these foreign-born players play professionally in Qatar.",
                "There are eight national teams which hail all players born locally, and another 10 have all but one player born locally. It worth poiting out that Japan and South Korea, which was stereotypically viewed as homogeneous society, each recruits one player not born locally, that is Suzuki and Castrop.",
                "Nonetheless, in total, there are 28 national teams with 80% players born locally. You could easily see it in the 'Whether players were born local' tab.",
                "Therefore, it seems that birth place and national identity is still strongly tie together, compared to where you work or live.",
                "You could explore the above observations by clicking sort with most mixed teams on the legend panel.",
            ]
        },
        {"variable_name":"play_local",    
        "analysis":[
            "This visualisation gives a more general view of where players play professionally by simply looking at whether they play locally. ",
            "All countries participating in the World Cup have their own football leagues, although six national teams are without any players playing in local leagues, 15 teams with one to five players playing locally, 10 teams have five to 12 players playing locally, while 13 teams have more than half of their players play locally.",
            "This distribution raises the questions of whether home-grown talents are selected to represent the nation or if the nation own league could produce talent to represent their countries.",
            "For example, it has been speculated that the success of the two deputants - Cape Verde and Curaçao depends on recruiting those playing in foreign leagues to represent the country. However, it is worth noticing that the other two debutants - Uzbekistan and Jordan have relatively more players playing in local leagues.",
            "Furthermore, although France has one of the strong football leagues and is where 99 players were born, only eight players from its national team play in local leagues, in contrast to England, Germany and Spain which have their representative players playing in their local leagues which are hailed as high quality. Another two UEFA national team Czech Republic and Turkey also have more than half of their representatives playing locally.",
            "Outside of UEFA, Qatar, Saudi Arabia, South Africa, Egypt, Iran and Uzbekistan also have more than half of their players playing locally, although all but Egypt and Iran have leagues established fewer than 50 years ago,, which could mean new stream of investment or interest.",
            "Besides these countries, other countries then to have fewer than half of the team playing locally.",
            "Therefore, to some extent, it seems that national players tend to play locally when there is a strong league or newly established league in their country. It could probably be similar to typical migration in which people move to strong economy or economy currently booming.",
            "You could explore the above observations by clicking sort with most players playing in local leagues on the legend panel.",
        ]
    },
     {"variable_name":"born_local",    
        "analysis":[
            "This visualisation gives a more general view of where players were born by simply looking at whether they were locally. ",
            "As mentioned in the tab of where players were born, Curaçao stood up with only one player was born there while the rest of the team were born in Netherlands",
            "",
            "",
            "",
            "",
            "",
]}
]

//     {"variable_name":"birth_place", "label":"Where players were born",
//         "sort":"Sort with most mixed teams on top",
//         "sort_index":"birth_diversity_index",   
//         "data":birth_place_data},
//     {"variable_name":"league", "label":"Whether players play in Big 5 leagues",
//         "sort":"Sort with teams with most players in Big 5 on top",
//         "sort_index":"proportion_big_five",   
//         "data":league_data},
  
//     {"variable_name":"born_local", "label":"Whether players were born local",
//         "sort":"Sort with teams with most players born locally",
//         "sort_index":"proportion_born_local",   
//         "data":born_local_data},
//     {"variable_name":"age", "label":"Bonus: Players' age",
//         "sort":"Sort with teams with highest mean age on top",
//         "sort_index":"mean_age",   
//         "data":age_data},

// ]