const birth_place_color = [
  { "place": "France", "count": 99, "color": "#000091" },
  { "place": "Netherlands", "count": 67, "color": "#FF9B00" },
  { "place": "Germany", "count": 49, "color": "#FFCE00" },
  { "place": "England", "count": 48, "color": "#FFFFFF" },
  { "place": "Sweden", "count": 36, "color": "#006AA7" },
  { "place": "Spain", "count": 36, "color": "E60026" },
  { "place": "Belgium", "count": 36, "color": "#000000" },
  { "place": "Austria", "count": 31, "color": "#EF3340" },
  { "place": "Argentina", "count": 31, "color": "#6CACE4" },
  { "place": "Switzerland", "count": 29, "color": "#DA291C" },
  { "place": "Brazil", "count": 29, "color": "#009440" },
  { "place": "United States", "count": 29, "color": "#0A3161" },
  { "place": "Portugal", "count": 28, "color": "#046A38" },
  { "place": "Colombia", "count": 27, "color": "#FFCD00" },
  { "place": "Egypt", "count": 27, "color": "#C09300" },
  { "place": "Saudi Arabia", "count": 27, "color": "#005430" },
  { "place": "Czech Republic", "count": 26, "color": "#11457E" },
  { "place": "South Africa", "count": 26, "color": "#FFB612" },
  { "place": "Norway", "count": 26, "color": "#00205B" },
  { "place": "Uruguay", "count": 26, "color": "#7B3F00" },
  { "place": "Uzbekistan", "count": 26, "color": "#0072CE" },
  { "place": "Japan", "count": 25, "color": "#BC002D" },
  { "place": "Panama", "count": 25, "color": "#DA121A" },
  { "place": "South Korea", "count": 25, "color": "#0F64CD" },
  { "place": "Iran", "count": 24, "color": "#239F40" },
  { "place": "Ecuador", "count": 23, "color": "#0072CE" },
  { "place": "Canada", "count": 23, "color": "#D80621" },
  { "place": "Jordan", "count": 23, "color": "#007A3D" },
  { "place": "Mexico", "count": 22, "color": "#006847" },
  { "place": "Paraguay", "count": 21, "color": "#FEDF00" },
  { "place": "Asia-Pacific", "count": 0, "color": "#FABFD2" },
  { "place": "Australia", "count": 20, "color": "#FABFD2" },
  { "place": "New Zealand", "count": 20, "color": "#FABFD2" },
  { "place": "Iraq", "count": 18, "color": "#FABFD2" },
  { "place": "Qatar", "count": 14, "color": "#FABFD2" },
  { "place": "Kazakhstan", "count": 1, "color": "#FABFD2" },
  { "place": "Africa", "count": 0, "color": "#b07AA1" },
  { "place": "Ghana", "count": 20, "color": "#b07AA1" },
  { "place": "Ivory Coast", "count": 19, "color": "#b07AA1" },
  { "place": "Senegal", "count": 17, "color": "#b07AA1" },
  { "place": "Tunisia", "count": 12, "color": "#b07AA1" },
  { "place": "Cape Verde", "count": 12, "color": "#b07AA1" },
  { "place": "Algeria", "count": 11, "color": "#b07AA1" },
  { "place": "Morocco", "count": 7, "color": "#b07AA1" },
  {
    "place": "Democratic Republic of the Congo",
    "count": 6,
    "color": "#b07AA1"
  },
  { "place": "Sudan", "count": 2, "color": "#b07AA1" },
  { "place": "Cameroon", "count": 2, "color": "#b07AA1" },
  { "place": "Burkina Faso", "count": 1, "color": "#b07AA1" },
  { "place": "Tanzania", "count": 1, "color": "#b07AA1" },
  { "place": "Kenya", "count": 1, "color": "#b07AA1" },
  { "place": "Nigeria", "count": 1, "color": "#b07AA1" },
  { "place": "Zambia", "count": 1, "color": "#b07AA1" },
  { "place": "Republic of the Congo", "count": 1, "color": "#b07AA1" },
  { "place": "Europe", "count": 0, "color": "#9c755f" },
  { "place": "Scotland", "count": 22, "color": "#9c755f" },
  { "place": "Croatia", "count": 17, "color": "#9c755f" },
  { "place": "Turkey", "count": 16, "color": "#9c755f" },
  { "place": "Bosnia and Herzegovina", "count": 14, "color": "#9c755f" },
  { "place": "Italy", "count": 3, "color": "#9c755f" },
  { "place": "Denmark", "count": 3, "color": "#9c755f" },
  { "place": "Slovenia", "count": 2, "color": "#9c755f" },
  { "place": "Ireland", "count": 1, "color": "#9c755f" },
  { "place": "Wales", "count": 1, "color": "#9c755f" },
  { "place": "Serbia", "count": 1, "color": "#9c755f" },
  { "place": "Isle of Man", "count": 1, "color": "#9c755f" },
  { "place": "Carribean", "count": 0, "color": "#86BCB6" },
  { "place": "Haiti", "count": 9, "color": "#86BCB6" },
  { "place": "Cura\u00e7ao", "count": 1, "color": "#86BCB6" },
  { "place": "Guinea", "count": 1, "color": "#86BCB6" }
]
