const colorEntity = [
    {'entity':'All','color':'#FFFFFF'},
    {'entity':'England','color':'#FFFFFF'},
    {'entity':'Germany','color':'#FFCE00'},
    {'entity':'Spain','color':'#E60026'},
    {'entity':'France','color':'#000091'},
    {'entity':'Italy','color':'#008C45'},
    {'entity':'Saudi_Arabia','color':'#005430'},
    {'entity':'Turkey','color':'#A91101'},
    {'entity':'United_States','color':'#0A3161'},
    {'entity':'Netherlands','color':'#FF9B00'},
    {'entity':'Brazil','color':'#fedf00'},
    {'entity':'Portugal','color':'#046A38'},
    {'entity':'Qatar','color':'#8A1538'},
    {'entity':'Belgium','color':'#000000'},
    // {'entity':'Belgium','color':'#EF3340'},
    // {'entity':'Belgium','color':'#FFBE7D'},
    {'entity':'Mexico','color':'#006847'},
    // {'entity':'Mexico','color':'#8CD17D'},
    {'entity':'Iran','color':'#239F40'},
    // {'entity':'Iran','color':'#E15759'},
    {'entity':'Czech_Republic','color':'#11457E'},
    {'entity':'Egypt','color':'#C09300'},
    {'entity':'Scotland','color':'#005EB8'},
    {'entity':'South_Africa','color':'#FFB612'},
    {'entity':'Uzbekistan','color':'#0072CE'},
    {'entity':'Argentina','color':'#6CACE4'},
    {'entity':'United_Arab_Emirates','color':'#525252'},
    {'entity':'Iraq','color':'#bdbdbd'},
    {'entity':'AFC','color':'#FABFD2'},
    {'entity':'Jordan','color':'#FABFD2'},
    {'entity':'South_Korea','color':'#FABFD2'},
    {'entity':'Japan','color':'#FABFD2'},
    {'entity':'Australia','color':'#FABFD2'},
    {'entity':'Malaysia','color':'#FABFD2'},
    {'entity':'Thailand','color':'#FABFD2'},
    {'entity':'China','color':'#FABFD2'},
    {'entity':'Indonesia','color':'#FABFD2'},
    {'entity':'CAF','color':'#b07AA1'},      
    {'entity':'Tunisia','color':'#b07AA1'},      
    {'entity':'Algeria','color':'#b07AA1'},      
    {'entity':'Morocco','color':'#b07AA1'},      
    {'entity':'Ghana','color':'#b07AA1'},      
    {'entity':'CONCACAF','color':'#499894'},
    {'entity':'Canada','color':'#499894'},
    {'entity':'Costa_Rica','color':'#499894'},
    {'entity':'Panama','color':'#499894'},
    {'entity':'Haiti','color':'#499894'},
    {'entity':'Honduras','color':'#499894'},
    {'entity':'CONMEBOL','color':'#86BCB6'}, 
    {'entity':'Ecuador','color':'#86BCB6'}, 
    {'entity':'Paraguay','color':'#86BCB6'}, 
    {'entity':'Venezuela','color':'#86BCB6'}, 
    {'entity':'Chile','color':'#86BCB6'}, 
    {'entity':'Uruguay','color':'#86BCB6'}, 
    {'entity':'Colombia','color':'#86BCB6'}, 
    {'entity':'OFC','color':'#D7B5A6'},
    {'entity':'New_Zealand','color':'#D7B5A6'},
    {'entity':'UEFA','color':'#9c755f'},
    {'entity':'Denmark','color':'#9c755f'},
    {'entity':'Russia','color':'#9c755f'},
    {'entity':'Greece','color':'#9c755f'},
    {'entity':'Switzerland','color':'#9c755f'},
    {'entity':'Cyprus','color':'#9c755f'},
    {'entity':'Austria','color':'#9c755f'},
    {'entity':'Norway','color':'#9c755f'},
    {'entity':'Wales','color':'#9c755f'},
    {'entity':'Croatia','color':'#9c755f'},
    {'entity':'Israel','color':'#9c755f'},
    {'entity':'Sweden','color':'#9c755f'},
    {'entity':'Serbia','color':'#9c755f'},
    {'entity':'Hungary','color':'#9c755f'},
    {'entity':'Romania','color':'#9c755f'},
    {'entity':'Poland','color':'#9c755f'},
    {'entity':'Azerbaijan','color':'#9c755f'},
    {'entity':'Slovakia','color':'#9c755f'},
    {'entity':'Ireland','color':'#9c755f'},
    {'entity':'Slovenia','color':'#9c755f'},
    {'entity':'Bulgaria','color':'#9c755f'},
    {'entity':'Armenia','color':'#9c755f'},
    {'entity':'Bosnia_and_Herzegovina','color':'#9c755f'},
    {'entity':'Kazakhstan','color':'#9c755f'},
    {'entity':'Finland','color':'#9c755f'},    
    {'entity':'Unattached','color':'#C8D0D9'},

    // {'entity':'AFC_11_22','color':'#B6992D'},
    // {'entity':'AFC_1_10','color':'#F1CE63'},
    // {'entity':'CAF_11_20','color':'#499894'},
    // {'entity':'CAF_1_10','color':'#86BCB6'},

]

const federation = [
    {'entity':'AFC',
    'countries': ["Jordan","South Korea","Japan","Australia","Malaysia","Thailand","China","Indonesia"]},
    {'entity':'CAF',
    'countries': ["Tunisia","Algeria","Morocco","Ghana"]},
    {'entity':'CONCACAF',
    'countries':["Canada","Costa Rica","Panama","Haiti","Honduras"]},
    {'entity':'CONMEBOL',
    'countries':["Ecuador","Paraguay","Venezuela","Chile","Uruguay","Colombia"]},
    {'entity':'OFC',
    'countries':["New Zealand"]},
    {'entity':'UEFA',
    'countries': ["Denmark","Russia","Greece","Switzerland","Cyprus","Austria","Norway","Wales",
"Wales","Croatia","Israel","Sweden","Serbia","Hungary","Romania","Poland","Azerbaijan","Slovakia",
"Ireland","Slovenia","Bulgaria","Armenia","Bosnia and Herzegovina","Kazakhstan","Finland"    
]}
]

const play_in_total = [
  { "play_in": "England", "count": 199 },
  { "play_in": "Germany", "count": 111 },
  { "play_in": "Spain", "count": 88 },
  { "play_in": "France", "count": 85 },
  { "play_in": "Italy", "count": 71 },
  { "play_in": "Saudi_Arabia", "count": 50 },
  { "play_in": "Turkey", "count": 46 },
  { "play_in": "United_States", "count": 44 },
  { "play_in": "Netherlands", "count": 38 },
  { "play_in": "Brazil", "count": 32 },
  { "play_in": "Portugal", "count": 30 },
  { "play_in": "Qatar", "count": 29 },
  { "play_in": "Belgium", "count": 28 },
  { "play_in": "Mexico", "count": 25 },
  { "play_in": "Czech_Republic", "count": 22 },
  { "play_in": "Iran", "count": 22 },
  { "play_in": "Scotland", "count": 20 },
  { "play_in": "Egypt", "count": 20 },
  { "play_in": "South_Africa", "count": 19 },
  { "play_in": "Argentina", "count": 17 },
  { "play_in": "Uzbekistan", "count": 17 },
  { "play_in": "United_Arab_Emirates", "count": 15 },
  { "play_in": "Iraq", "count": 15 },
  { "play_in": "Denmark", "count": 14 },
  { "play_in": "Russia", "count": 12 },
  { "play_in": "Greece", "count": 12 },
  { "play_in": "Jordan", "count": 12 },
  { "play_in": "Switzerland", "count": 11 },
  { "play_in": "Cyprus", "count": 10 },
  { "play_in": "South_Korea", "count": 8 },
  { "play_in": "Austria", "count": 8 },
  { "play_in": "Norway", "count": 7 },
  { "play_in": "Japan", "count": 7 },
  { "play_in": "Tunisia", "count": 7 },
  { "play_in": "Canada", "count": 6 },
  { "play_in": "Australia", "count": 6 },
  { "play_in": "New_Zealand", "count": 6 },
  { "play_in": "Wales", "count": 5 },
  { "play_in": "Croatia", "count": 5 },
  { "play_in": "Ecuador", "count": 5 },
  { "play_in": "Paraguay", "count": 4 },
  { "play_in": "Israel", "count": 4 },
  { "play_in": "Sweden", "count": 4 },
  { "play_in": "Serbia", "count": 3 },
  { "play_in": "Romania", "count": 3 },
  { "play_in": "Hungary", "count": 3 },
  { "play_in": "Morocco", "count": 3 },
  { "play_in": "Poland", "count": 3 },
  { "play_in": "Algeria", "count": 3 },
  { "play_in": "Azerbaijan", "count": 2 },
  { "play_in": "Slovakia", "count": 2 },
  { "play_in": "Malaysia", "count": 2 },
  { "play_in": "Slovenia", "count": 2 },
  { "play_in": "Unattached", "count": 2 },
  { "play_in": "Bulgaria", "count": 2 },
  { "play_in": "Ireland", "count": 2 },
  { "play_in": "Venezuela", "count": 2 },
  { "play_in": "Panama", "count": 2 },
  { "play_in": "Costa_Rica", "count": 2 },
  { "play_in": "Chile", "count": 2 },
  { "play_in": "China", "count": 1 },
  { "play_in": "Kazakhstan", "count": 1 },
  { "play_in": "Bosnia_and_Herzegovina", "count": 1 },
  { "play_in": "Haiti", "count": 1 },
  { "play_in": "Finland", "count": 1 },
  { "play_in": "Thailand", "count": 1 },
  { "play_in": "Indonesia", "count": 1 },
  { "play_in": "Colombia", "count": 1 },
  { "play_in": "Armenia", "count": 1 },
  { "play_in": "Ghana", "count": 1 },
  { "play_in": "Uruguay", "count": 1 },
  { "play_in": "Honduras", "count": 1 }
]

const barWidthScale = d3.scaleLinear()
        .domain([0,200])
        .range([0,100])

const colorScale = d3.scaleOrdinal()
        .domain(colorEntity.map(d => d.entity))
        .range(colorEntity.map(d => d.color))