const play_in_data = [
  { "play_in": "England", "color": "#FFFFFF", "count": 199.0 },
  { "play_in": "Germany", "color": "#FFCE00", "count": 111.0 },
  { "play_in": "Spain", "color": "#E60026", "count": 88.0 },
  { "play_in": "France", "color": "#000091", "count": 85.0 },
  { "play_in": "Italy", "color": "#008C45", "count": 71.0 },
  { "play_in": "Saudi_Arabia", "color": "#005430", "count": 50.0 },
  { "play_in": "Turkey", "color": "#A91101", "count": 46.0 },
  { "play_in": "United_States", "color": "#0A3161", "count": 44.0 },
  { "play_in": "Netherlands", "color": "#FF9B00", "count": 38.0 },
  { "play_in": "Brazil", "color": "#fedf00", "count": 32.0 },
  { "play_in": "Portugal", "color": "#046A38", "count": 30.0 },
  { "play_in": "Qatar", "color": "#8A1538", "count": 29.0 },
  { "play_in": "Belgium", "color": "#000000", "count": 28.0 },
  { "play_in": "Mexico", "color": "#006847", "count": 25.0 },
  { "play_in": "Iran", "color": "#239F40", "count": 22.0 },
  { "play_in": "Czech_Republic", "color": "#11457E", "count": 22.0 },
  { "play_in": "Egypt", "color": "#C09300", "count": 20.0 },
  { "play_in": "Scotland", "color": "#005EB8", "count": 20.0 },
  { "play_in": "South_Africa", "color": "#FFB612", "count": 19.0 },
  { "play_in": "Uzbekistan", "color": "#0072CE", "count": 17.0 },
  { "play_in": "Argentina", "color": "#6CACE4", "count": 17.0 },
  { "play_in": "United_Arab_Emirates", "color": "#525252", "count": 15.0 },
  { "play_in": "Iraq", "color": "#bdbdbd", "count": 15.0 },
  { "play_in": "AFC", "color": "#FABFD2", "count": 0.0 },
  { "play_in": "Jordan", "color": "#FABFD2", "count": 12.0 },
  { "play_in": "South_Korea", "color": "#FABFD2", "count": 8.0 },
  { "play_in": "Japan", "color": "#FABFD2", "count": 7.0 },
  { "play_in": "Australia", "color": "#FABFD2", "count": 6.0 },
  { "play_in": "Malaysia", "color": "#FABFD2", "count": 2.0 },
  { "play_in": "Thailand", "color": "#FABFD2", "count": 1.0 },
  { "play_in": "China", "color": "#FABFD2", "count": 1.0 },
  { "play_in": "Indonesia", "color": "#FABFD2", "count": 1.0 },
  { "play_in": "CAF", "color": "#b07AA1", "count": 0.0 },
  { "play_in": "Tunisia", "color": "#b07AA1", "count": 7.0 },
  { "play_in": "Algeria", "color": "#b07AA1", "count": 3.0 },
  { "play_in": "Morocco", "color": "#b07AA1", "count": 3.0 },
  { "play_in": "Ghana", "color": "#b07AA1", "count": 1.0 },
  { "play_in": "CONCACAF", "color": "#499894", "count": 0.0 },
  { "play_in": "Canada", "color": "#499894", "count": 6.0 },
  { "play_in": "Costa_Rica", "color": "#499894", "count": 2.0 },
  { "play_in": "Panama", "color": "#499894", "count": 2.0 },
  { "play_in": "Haiti", "color": "#499894", "count": 1.0 },
  { "play_in": "Honduras", "color": "#499894", "count": 1.0 },
  { "play_in": "CONMEBOL", "color": "#86BCB6", "count": 0.0 },
  { "play_in": "Ecuador", "color": "#86BCB6", "count": 5.0 },
  { "play_in": "Paraguay", "color": "#86BCB6", "count": 4.0 },
  { "play_in": "Venezuela", "color": "#86BCB6", "count": 2.0 },
  { "play_in": "Chile", "color": "#86BCB6", "count": 2.0 },
  { "play_in": "Uruguay", "color": "#86BCB6", "count": 1.0 },
  { "play_in": "Colombia", "color": "#86BCB6", "count": 1.0 },
  { "play_in": "OFC", "color": "#D7B5A6", "count": 0.0 },
  { "play_in": "New_Zealand", "color": "#D7B5A6", "count": 6.0 },
  { "play_in": "UEFA", "color": "#9c755f", "count": 0.0 },
  { "play_in": "Denmark", "color": "#9c755f", "count": 14.0 },
  { "play_in": "Russia", "color": "#9c755f", "count": 12.0 },
  { "play_in": "Greece", "color": "#9c755f", "count": 12.0 },
  { "play_in": "Switzerland", "color": "#9c755f", "count": 11.0 },
  { "play_in": "Cyprus", "color": "#9c755f", "count": 10.0 },
  { "play_in": "Austria", "color": "#9c755f", "count": 8.0 },
  { "play_in": "Norway", "color": "#9c755f", "count": 7.0 },
  { "play_in": "Wales", "color": "#9c755f", "count": 5.0 },
  { "play_in": "Croatia", "color": "#9c755f", "count": 5.0 },
  { "play_in": "Israel", "color": "#9c755f", "count": 4.0 },
  { "play_in": "Sweden", "color": "#9c755f", "count": 4.0 },
  { "play_in": "Serbia", "color": "#9c755f", "count": 3.0 },
  { "play_in": "Hungary", "color": "#9c755f", "count": 3.0 },
  { "play_in": "Romania", "color": "#9c755f", "count": 3.0 },
  { "play_in": "Poland", "color": "#9c755f", "count": 3.0 },
  { "play_in": "Azerbaijan", "color": "#9c755f", "count": 2.0 },
  { "play_in": "Slovakia", "color": "#9c755f", "count": 2.0 },
  { "play_in": "Ireland", "color": "#9c755f", "count": 2.0 },
  { "play_in": "Slovenia", "color": "#9c755f", "count": 2.0 },
  { "play_in": "Bulgaria", "color": "#9c755f", "count": 2.0 },
  { "play_in": "Armenia", "color": "#9c755f", "count": 1.0 },
  { "play_in": "Bosnia_and_Herzegovina", "color": "#9c755f", "count": 1.0 },
  { "play_in": "Kazakhstan", "color": "#9c755f", "count": 1.0 },
  { "play_in": "Finland", "color": "#9c755f", "count": 1.0 },
  { "play_in": "Unattached", "color": "#C8D0D9", "count": 2.0 }
]


const barWidthScalePlayIn = d3.scaleLinear()
        .domain([0,200])
        .range([0,100])

const colorScalePlayIn = d3.scaleOrdinal()
        .domain(play_in_data.map(d => d.play_in))
        .range(play_in_data.map(d => d.color))